package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/tidjee-dev/scaffoldgen/internal/model"
)

const eol = "\r\n"

func GeneratePS1(root *model.Node, verbose bool) (string, error) {
	if root == nil {
		return "", fmt.Errorf("nil root node")
	}

	var b strings.Builder
	writeHeader(&b)

	Walk(root, "", func(e Event) {
		switch e.Kind {
		case EventDir:
			writeDir(&b, e.Path, verbose, e.Label())

		case EventFile:
			if e.Template != nil {
				dir := filepath.Base(filepath.Dir(e.Path))
				// Use enhanced template context if available
				if e.TemplateContext != nil {
					writeEnhancedTemplatedFile(&b, psQuote(e.Path), dir, e.TemplateContext, verbose, e.Label())
				} else {
					writeTemplatedFile(&b, psQuote(e.Path), dir, e.Template, verbose, e.Label())
				}
			} else {
				writeFile(&b, e.Path, verbose, e.Label())
			}
		}
	})

	return b.String(), nil
}

func writeHeader(b *strings.Builder) {
	b.WriteString("# Auto-generated by scaffoldgen" + eol)
	b.WriteString("# Review this script before execution." + eol)
	b.WriteString(eol)
}

func writeDir(b *strings.Builder, path string, verbose bool, label string) {
	p := psQuote(path)
	action := fmt.Sprintf("New-Item -ItemType Directory -Path %s | Out-Null", p)
	emitPS1Create(b, p, label, verbose, action)
}

func writeFile(b *strings.Builder, path string, verbose bool, label string) {
	p := psQuote(path)
	action := fmt.Sprintf("New-Item -ItemType File -Path %s | Out-Null", p)
	emitPS1Create(b, p, label, verbose, action)
}

func writeTemplatedFile(b *strings.Builder, quotedPath, pkg string, template TemplateProvider, verbose bool, label string) {
	content := template(pkg)
	action := fmt.Sprintf("Set-Content -Path %s -Value \"%s\"", quotedPath, escapePS(content))
	emitPS1Create(b, quotedPath, label, verbose, action)
}

func writeEnhancedTemplatedFile(b *strings.Builder, quotedPath, pkg string, ctx *TemplateContext, verbose bool, label string) {
	if ctx == nil {
		return
	}
	ctx.Package = pkg
	ext := GetFileExtension(ctx.Filename)
	content := RenderTemplateWithContext(ext, *ctx)
	action := fmt.Sprintf("Set-Content -Path %s -Value \"%s\"", quotedPath, escapePS(content))
	emitPS1Create(b, quotedPath, label, verbose, action)
}

func writeGoFile(b *strings.Builder, quotedPath, pkg string, verbose bool, label string) {
	content := fmt.Sprintf("package %s%s", pkg, eol)
	action := fmt.Sprintf("Set-Content -Path %s -Value \"%s\"", quotedPath, escapePS(content))
	emitPS1Create(b, quotedPath, label, verbose, action)
}

func psQuote(s string) string { return fmt.Sprintf("\"%s\"", s) }

func escapePS(s string) string {
	return strings.ReplaceAll(s, "\"", "`\"")
}

func emitPS1Create(b *strings.Builder, quotedPath, label string, verbose bool, action string) {
	if verbose {
		fmt.Fprintf(b,
			"if (!(Test-Path %s)) {%s  Write-Host \"[scaffoldgen] %s\"%s  %s%s}%s",
			quotedPath, eol, label, eol, action, eol, eol,
		)
		return
	}

	fmt.Fprintf(b,
		"if (!(Test-Path %s)) {%s  %s%s}%s",
		quotedPath, eol, action, eol, eol,
	)
}
