package generator

import (
	"strings"
	"testing"

	"github.com/tidjee-dev/scaffoldgen/internal/model"
)

func TestGeneratePS1(t *testing.T) {
	// Test with nil root
	_, err := GeneratePS1(nil, false)
	if err == nil {
		t.Error("Expected error for nil root node")
	}
	if !strings.Contains(err.Error(), "nil root node") {
		t.Errorf("Expected error to mention nil root node, got %v", err)
	}
}

func TestGeneratePS1Empty(t *testing.T) {
	// Test with empty structure
	root := model.NewDir("test")

	result, err := GeneratePS1(root, false)
	if err != nil {
		t.Errorf("Expected no error for empty structure, got %v", err)
	}

	// Check that result contains header
	if !strings.Contains(result, "# Auto-generated by scaffoldgen") {
		t.Error("Expected result to contain header comment")
	}

	// Check that result contains PowerShell EOL
	if !strings.Contains(result, "\r\n") {
		t.Error("Expected result to contain Windows line endings")
	}
}

func TestGeneratePS1WithFiles(t *testing.T) {
	// Test with file structure
	root := model.NewDir("test")
	root.AddChild(model.NewFile("test.txt"))

	result, err := GeneratePS1(root, false)
	if err != nil {
		t.Errorf("Expected no error for file structure, got %v", err)
	}

	// Check that result contains file creation command
	if !strings.Contains(result, "New-Item -ItemType File") {
		t.Error("Expected result to contain file creation command")
	}

	// Check that result contains the file path
	if !strings.Contains(result, "test.txt") {
		t.Error("Expected result to contain file path")
	}
}

func TestGeneratePS1WithDirectories(t *testing.T) {
	// Test with directory structure
	root := model.NewDir("test")
	subdir := model.NewDir("subdir")
	root.AddChild(subdir)

	result, err := GeneratePS1(root, false)
	if err != nil {
		t.Errorf("Expected no error for directory structure, got %v", err)
	}

	// Check that result contains directory creation command
	if !strings.Contains(result, "New-Item -ItemType Directory") {
		t.Error("Expected result to contain directory creation command")
	}

	// Check that result contains the directory path
	if !strings.Contains(result, "subdir") {
		t.Error("Expected result to contain directory path")
	}
}

func TestGeneratePS1Verbose(t *testing.T) {
	// Test verbose mode
	root := model.NewDir("test")
	root.AddChild(model.NewFile("test.txt"))

	result, err := GeneratePS1(root, true)
	if err != nil {
		t.Errorf("Expected no error for verbose mode, got %v", err)
	}

	// Check that result contains verbose output
	if !strings.Contains(result, "Write-Host") {
		t.Error("Expected result to contain verbose output commands")
	}

	if !strings.Contains(result, "[scaffoldgen]") {
		t.Error("Expected result to contain scaffoldgen prefix")
	}
}

func TestPSQuote(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"test.txt", "\"test.txt\""},
		{"path/to/file.txt", "\"path/to/file.txt\""},
		{"", "\"\""},
		{"file with spaces.txt", "\"file with spaces.txt\""},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			result := psQuote(tt.input)
			if result != tt.expected {
				t.Errorf("Expected %q, got %q", tt.expected, result)
			}
		})
	}
}

func TestEscapePS(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"test content", "test content"},
		{"content with \"quotes\"", "content with `\"quotes`\""},
		{"multiple \"quotes\" here", "multiple `\"quotes`\" here"},
		{"no quotes", "no quotes"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			result := escapePS(tt.input)
			if result != tt.expected {
				t.Errorf("Expected %q, got %q", tt.expected, result)
			}
		})
	}
}

func TestWriteHeader(t *testing.T) {
	var b strings.Builder
	writeHeader(&b)

	result := b.String()

	// Check header content
	expectedLines := []string{
		"# Auto-generated by scaffoldgen",
		"# Review this script before execution.",
	}

	for _, line := range expectedLines {
		if !strings.Contains(result, line) {
			t.Errorf("Expected header to contain %q", line)
		}
	}

	// Check for Windows line endings
	if !strings.Contains(result, "\r\n") {
		t.Error("Expected header to contain Windows line endings")
	}
}

func TestEmitPS1CreateVerbose(t *testing.T) {
	var b strings.Builder
	path := "\"test.txt\""
	label := "Creating test file"
	action := "New-Item -ItemType File -Path \"test.txt\" | Out-Null"

	emitPS1Create(&b, path, label, true, action)

	result := b.String()

	// Check verbose format
	if !strings.Contains(result, "Write-Host") {
		t.Error("Expected verbose output to contain Write-Host")
	}

	if !strings.Contains(result, "[scaffoldgen]") {
		t.Error("Expected verbose output to contain scaffoldgen prefix")
	}

	if !strings.Contains(result, label) {
		t.Error("Expected verbose output to contain label")
	}
}

func TestEmitPS1CreateNonVerbose(t *testing.T) {
	var b strings.Builder
	path := "\"test.txt\""
	label := "Creating test file"
	action := "New-Item -ItemType File -Path \"test.txt\" | Out-Null"

	emitPS1Create(&b, path, label, false, action)

	result := b.String()

	// Check non-verbose format
	if strings.Contains(result, "Write-Host") {
		t.Error("Expected non-verbose output to not contain Write-Host")
	}

	if strings.Contains(result, "[scaffoldgen]") {
		t.Error("Expected non-verbose output to not contain scaffoldgen prefix")
	}

	if !strings.Contains(result, action) {
		t.Error("Expected output to contain action")
	}
}
