package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/tidjee-dev/scaffoldgen/internal/model"
)

const shEOL = "\n"

func GenerateSH(root *model.Node, verbose bool) (string, error) {
	if root == nil {
		return "", fmt.Errorf("nil root node")
	}

	var b strings.Builder
	writeSHHeader(&b)

	Walk(root, "", func(e Event) {
		p := filepath.ToSlash(e.Path)

		switch e.Kind {
		case EventDir:
			writeSHDir(&b, p, verbose, e.Label())

		case EventFile:
			if e.Template != nil {
				dir := filepath.Base(filepath.Dir(e.Path))
				// Use enhanced template context if available
				if e.TemplateContext != nil {
					writeSHEnhancedTemplatedFile(&b, shQuote(p), dir, p, e.TemplateContext, verbose, e.Label())
				} else {
					writeSHTemplatedFile(&b, shQuote(p), dir, p, e.Template, verbose, e.Label())
				}
			} else {
				writeSHFile(&b, p, verbose, e.Label())
			}
		}
	})

	return b.String(), nil
}

func writeSHHeader(b *strings.Builder) {
	b.WriteString("#!/usr/bin/env bash" + shEOL)
	b.WriteString("# Auto-generated by scaffoldgen" + shEOL)
	b.WriteString("# Review this script before execution." + shEOL)
	b.WriteString("set -e" + shEOL + shEOL)
}

func writeSHDir(b *strings.Builder, path string, verbose bool, label string) {
	p := shQuote(path)
	action := fmt.Sprintf("mkdir -p %s", p)
	emitSHCreate(b, p, label, verbose, action)
}

func writeSHFile(b *strings.Builder, path string, verbose bool, label string) {
	p := shQuote(path)
	action := fmt.Sprintf("touch %s", p)
	emitSHCreate(b, p, label, verbose, action)
}

func writeSHTemplatedFile(b *strings.Builder, quotedPath, pkg, rawPath string, template TemplateProvider, verbose bool, label string) {
	content := template(pkg)
	action := fmt.Sprintf("printf \"%s\" > %s", escapeSH(content), quotedPath)
	emitSHCreate(b, quotedPath, label, verbose, action)
}

func writeSHEnhancedTemplatedFile(b *strings.Builder, quotedPath, pkg, rawPath string, ctx *TemplateContext, verbose bool, label string) {
	if ctx == nil {
		return
	}
	ctx.Package = pkg
	ext := GetFileExtension(ctx.Filename)
	content := RenderTemplateWithContext(ext, *ctx)
	action := fmt.Sprintf("printf \"%s\" > %s", escapeSH(content), quotedPath)
	emitSHCreate(b, quotedPath, label, verbose, action)
}

func writeSHGoFile(b *strings.Builder, quotedPath, pkg, rawPath string, verbose bool, label string) {
	content := fmt.Sprintf("package %s\n", pkg)
	action := fmt.Sprintf("printf \"%s\" > %s", escapeSH(content), quotedPath)
	emitSHCreate(b, quotedPath, label, verbose, action)
}

func shQuote(s string) string { return fmt.Sprintf("\"%s\"", s) }

func escapeSH(s string) string {
	return strings.ReplaceAll(s, "\"", "\\\"")
}

func emitSHCreate(b *strings.Builder, quotedPath, label string, verbose bool, action string) {
	if verbose {
		fmt.Fprintf(b,
			"[ -e %s ] || { echo \"[scaffoldgen] %s\"; %s; }%s",
			quotedPath, label, action, shEOL,
		)
		return
	}

	fmt.Fprintf(b,
		"[ -e %s ] || %s%s",
		quotedPath, action, shEOL,
	)
}
