package generator

import (
	"strings"
	"testing"

	"github.com/tidjee-dev/scaffoldgen/internal/model"
)

func TestGenerateSH(t *testing.T) {
	// Test with nil root
	_, err := GenerateSH(nil, false)
	if err == nil {
		t.Error("Expected error for nil root node")
	}
	if !strings.Contains(err.Error(), "nil root node") {
		t.Errorf("Expected error to mention nil root node, got %v", err)
	}
}

func TestGenerateSHEmpty(t *testing.T) {
	// Test with empty structure
	root := model.NewDir("test")

	result, err := GenerateSH(root, false)
	if err != nil {
		t.Errorf("Expected no error for empty structure, got %v", err)
	}

	// Check that result contains header
	if !strings.Contains(result, "# Auto-generated by scaffoldgen") {
		t.Error("Expected result to contain header comment")
	}

	// Check that result contains shebang
	if !strings.Contains(result, "#!/usr/bin/env bash") {
		t.Error("Expected result to contain shebang")
	}

	// Check that result contains set -e
	if !strings.Contains(result, "set -e") {
		t.Error("Expected result to contain 'set -e'")
	}
}

func TestGenerateSHWithFiles(t *testing.T) {
	// Test with file structure
	root := model.NewDir("test")
	root.AddChild(model.NewFile("test.txt"))

	result, err := GenerateSH(root, false)
	if err != nil {
		t.Errorf("Expected no error for file structure, got %v", err)
	}

	// Check that result contains file creation command
	if !strings.Contains(result, "touch") {
		t.Error("Expected result to contain file creation command")
	}

	// Check that result contains the file path
	if !strings.Contains(result, "test.txt") {
		t.Error("Expected result to contain file path")
	}
}

func TestGenerateSHWithDirectories(t *testing.T) {
	// Test with directory structure
	root := model.NewDir("test")
	subdir := model.NewDir("subdir")
	root.AddChild(subdir)

	result, err := GenerateSH(root, false)
	if err != nil {
		t.Errorf("Expected no error for directory structure, got %v", err)
	}

	// Check that result contains directory creation command
	if !strings.Contains(result, "mkdir -p") {
		t.Error("Expected result to contain directory creation command")
	}

	// Check that result contains the directory path
	if !strings.Contains(result, "subdir") {
		t.Error("Expected result to contain directory path")
	}
}

func TestGenerateSHVerbose(t *testing.T) {
	// Test verbose mode
	root := model.NewDir("test")
	root.AddChild(model.NewFile("test.txt"))

	result, err := GenerateSH(root, true)
	if err != nil {
		t.Errorf("Expected no error for verbose mode, got %v", err)
	}

	// Check that result contains verbose output
	if !strings.Contains(result, "echo") {
		t.Error("Expected result to contain verbose output commands")
	}

	if !strings.Contains(result, "[scaffoldgen]") {
		t.Error("Expected result to contain scaffoldgen prefix")
	}
}

func TestShQuote(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"test.txt", "\"test.txt\""},
		{"path/to/file.txt", "\"path/to/file.txt\""},
		{"", "\"\""},
		{"file with spaces.txt", "\"file with spaces.txt\""},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			result := shQuote(tt.input)
			if result != tt.expected {
				t.Errorf("Expected %q, got %q", tt.expected, result)
			}
		})
	}
}

func TestEscapeSH(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"test content", "test content"},
		{"content with \"quotes\"", "content with \\\"quotes\\\""},
		{"multiple \"quotes\" here", "multiple \\\"quotes\\\" here"},
		{"no quotes", "no quotes"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			result := escapeSH(tt.input)
			if result != tt.expected {
				t.Errorf("Expected %q, got %q", tt.expected, result)
			}
		})
	}
}

func TestWriteSHHeader(t *testing.T) {
	var b strings.Builder
	writeSHHeader(&b)

	result := b.String()

	// Check header content
	expectedLines := []string{
		"#!/usr/bin/env bash",
		"# Auto-generated by scaffoldgen",
		"# Review this script before execution.",
		"set -e",
	}

	for _, line := range expectedLines {
		if !strings.Contains(result, line) {
			t.Errorf("Expected header to contain %q", line)
		}
	}

	// Check for Unix line endings
	if !strings.Contains(result, "\n") {
		t.Error("Expected header to contain Unix line endings")
	}
}

func TestEmitSHCreateVerbose(t *testing.T) {
	var b strings.Builder
	path := "\"test.txt\""
	label := "Creating test file"
	action := "touch \"test.txt\""

	emitSHCreate(&b, path, label, true, action)

	result := b.String()

	// Check verbose format
	if !strings.Contains(result, "echo") {
		t.Error("Expected verbose output to contain echo")
	}

	if !strings.Contains(result, "[scaffoldgen]") {
		t.Error("Expected verbose output to contain scaffoldgen prefix")
	}

	if !strings.Contains(result, label) {
		t.Error("Expected verbose output to contain label")
	}
}

func TestEmitSHCreateNonVerbose(t *testing.T) {
	var b strings.Builder
	path := "\"test.txt\""
	label := "Creating test file"
	action := "touch \"test.txt\""

	emitSHCreate(&b, path, label, false, action)

	result := b.String()

	// Check non-verbose format
	if strings.Contains(result, "echo") {
		t.Error("Expected non-verbose output to not contain echo")
	}

	if strings.Contains(result, "[scaffoldgen]") {
		t.Error("Expected non-verbose output to not contain scaffoldgen prefix")
	}

	if !strings.Contains(result, action) {
		t.Error("Expected output to contain action")
	}
}

func TestSHFilePathConversion(t *testing.T) {
	// Test that Windows paths are converted to Unix paths
	// Note: filepath.ToSlash converts path separators, but not backslashes in filenames
	root := model.NewDir("test")
	subdir := model.NewDir("subdir")
	subdir.AddChild(model.NewFile("test.txt"))
	root.AddChild(subdir)

	result, err := GenerateSH(root, false)
	if err != nil {
		t.Errorf("Expected no error for directory structure, got %v", err)
	}

	// Check that Unix-style paths are used
	if !strings.Contains(result, "test/subdir") {
		t.Error("Expected Unix-style paths in output")
	}
}
